# Generated by Django 5.0.7 on 2024-12-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(default='Name', max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(default='surname', max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('booked', 'Заброньовано'), ('paid', 'Оплачено')], max_length=10),
        ),
    ]
